{{- range $host := .Values.app.hosts }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "riskafka.fullname" $ }}-rocksdb-{{ $host }}
  labels:
    app: {{ template "riskafka.fullname" $ }}-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: local-path
---
{{- end }}
