apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "riskafka.fullname" . }}-kafka-set-acls
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: {{ template "riskafka.fullname" . }}-kafka-acl
          image: confluentinc/cp-kafka:latest
          command:
            - /bin/sh
            - -c
            - |
              # Allow ANONYMOUS users to read from all topics
              kafka-acls --bootstrap-server stream.ris-kafka.com:9092 \
                         --add --allow-principal User:ANONYMOUS \
                         --operation Read \
                         --topic '*' \
                         --group '*' \
                         --allow-host '*'

              # Allow ANONYMOUS users to WRITE only on the internal port 29092
              kafka-acls --bootstrap-server {{ template "riskafka.fullname" . }}-kafka:29092 \
                         --add --allow-principal User:ANONYMOUS \
                         --operation Write \
                         --topic '*' \
                         --allow-host '*'
  backoffLimit: 4
